//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FNVCG.MODEL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FNVCG.MODEL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to able
        ///acer
        ///acid
        ///acne
        ///acre
        ///acts
        ///adam
        ///adds
        ///adsl
        ///aged
        ///ages
        ///aids
        ///aims
        ///alan
        ///alex
        ///alot
        ///also
        ///alto
        ///anal
        ///andy
        ///anna
        ///anne
        ///anti
        ///apps
        ///aqua
        ///arab
        ///arch
        ///area
        ///arms
        ///army
        ///arts
        ///asia
        ///asin
        ///asks
        ///asus
        ///atom
        ///audi
        ///auto
        ///avon
        ///away
        ///axis
        ///babe
        ///baby
        ///back
        ///bags
        ///bald
        ///bali
        ///ball
        ///band
        ///bang
        ///bank
        ///bare
        ///barn
        ///bars
        ///base
        ///bass
        ///bath
        ///bdsm
        ///beam
        ///bean
        ///bear
        ///beat
        ///beds
        ///beef
        ///been
        ///beer
        ///bell
        ///belt
        ///bend
        ///benz
        ///best
        ///beta
        ///beth
        ///bias
        ///bids
        ///bike
        ///bill
        ///bind
        ///biol
        ///bios
        ///bird
        ///bite
        ///bits
        ///blah
        ///blog
        ///bl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _4_char_list {
            get {
                return ResourceManager.GetString("4_char_list", resourceCulture);
            }
        }
    }
}
